# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UsgsStreamMapper
                                 A QGIS plugin
 Map upstream/downstream tributaries and basins using USGS NWIS station ids
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-21
        copyright            : (C) 2020 by Austin Raney
        email                : aaraney@crimson.ua.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UsgsStreamMapper class from file UsgsStreamMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .usgs_stream_mapper import UsgsStreamMapper
    return UsgsStreamMapper(iface)
